### ISSUE TITLE
Obscure error regarding PyCArrayType

### ISSUE THREAD

**Issue by anprevos** [pymc-devs/pymc-bart#165]
I am unable to run any BART model. I have tried multiple interpreters (all 3.8+), without any luck and from what I read PyCArrayType corresponds to the ctypes module which is not a package I can just change the version of. What is going on?

`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\Users\preva\anaconda3\envs\pymc-bart\Lib\site-packages\joblib\externals\loky\backend\popen_loky_win32.py", line 168, in main
    self = load(from_parent)
           ^^^^^^^^^^^^^^^^^
AttributeError: type object 'PyCArrayType' has no attribute '__mul__'. Did you mean: '__mro__'?`

Thank you.

**Comment by anprevos** [comment]
Joblib parallel computation was interacting with BART which caused the error.
